### ISSUE TITLE
"The STR doesn't support the buffer API"

### ISSUE THREAD

**Issue by ElyosOfTheAbyss** [44670/layeredFS#4]
I get this error:
C:\layeredFS-master>locate.py workdir\dump.bin
Traceback (most recent call last):
  File "C:\layeredFS-master\locate.py", line 102, in <module>
    save('mountRom', findFunction(code, parseHexStr('0C 00 9D E5 00 10 90 E5  28
 10 91 E5 31 FF 2F E1  ')));
  File "C:\layeredFS-master\locate.py", line 24, in findFunction
    t = code.find(sig);
TypeError: Type str doesn't support the buffer API
And this happens to all games

**Comment by 44670** [comment]
python 3 is not supported, try python 2.7

**Comment by ElyosOfTheAbyss** [comment]
Ok, But now I have this error

`C:\layeredFS-master>locate.py workdir\dump.bin
Traceback (most recent call last):
  File "C:\layeredFS-master\locate.py", line 98, in <module>
    with open(sys.argv[1], 'rb') as f:
IndexError: list index out of range`

**Comment by 44670** [comment]
edit the bat file and try again:

python locate.py workdir\dump.bin

**Comment by ElyosOfTheAbyss** [comment]
That just gave me another error
`C:\layeredFS-master>python locate.py workdir\dump.bin
'python' is not recognized as an internal or external command,
operable program or batch file.
`

**Comment by 44670** [comment]
the python for windows may have not been installed correctly, check the path variable or re-install the python.

**Comment by ElyosOfTheAbyss** [comment]
Still didn't work. I have 2.7.0 Should it be something abit higher?

**Comment by 44670** [comment]
2.7.0 is ok. maybe you should try another computer...

**Comment by phecdaDia** [comment]
( Just answering for future people )

Use the explicite path, Like: C:\Python27\python.exe , not just "python", as this references the PATH variable.

**Comment by 44670** [comment]
ah, I see
